volumes:
    taskscheduler_pgdata:

services:
    postgres:
        build:
            context: ./db
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            PGDATA: /var/lib/postgresql/data/pgdata
        volumes:
            - taskscheduler_pgdata:/var/lib/postgresql/data/pgdata
        ports:
            - "5432:5432"

    redis:
        image: redis
        ports:
            - "6379:6379"
